version: "3.8"

networks:
  docknode-btc:
    driver: bridge

volumes:
  bitcoind_data: {}
  caddy_data: {}
  caddy_config: {}

services:
  bitcoind:
    image: "kylemanna/bitcoind:latest"
    container_name: bitcoind
    hostname: bitcoind
    restart: unless-stopped
    ports:
      - 8333:8333
      - 127.0.0.1:8332:8332
    volumes:
      - bitcoind_data:/bitcoin/.bitcoin
    command:
      - '-chain=main'
      - '-port=8333'
      - '-rest'
      - '-server'
      - '-printtoconsole'
      - '-disablewallet'
      - '-rpcport=8332'
      - '-rpcuser=bitcoinrpc'
      - '-rpcpassword=bitcoinrpc'
      - '-help'
    networks:
      - docknode-btc

  nodeexporter:
    image: prom/node-exporter:v1.4.0
    container_name: nodeexporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - docknode-btc

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    depends_on:
      - bitcoind
    ports:
      - "80:80"
      - "443:443"
      - "9100:9100"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - BASIC_AUTH_USERS=${BASIC_AUTH_USERS:?err}
      - HOST=${HOST:?err}
    networks:
      - docknode-btc