version: "3.8"

networks:
  docknode-btc:
    driver: bridge

volumes:
  bitcoind_data: {}
  caddy_data: {}
  caddy_config: {}

services:
  bitcoind:
    image: "lncm/bitcoind:v24.0"
    container_name: bitcoind
    hostname: bitcoind
    restart: on-failure
    ports:
      - "8333:8333/tcp"
    expose:
      - 8332
    volumes:
      - bitcoind_data:/data/.bitcoin
    command:
      - '-reindex-chainstate'
      - '-chain=main'
      - '-txindex'
      - '-coinstatsindex'
      - '-disablewallet'
      - '-port=8333'
      - '-rpcport=8332'
      - '-rpcallowip=0.0.0.0/0'
      - '-rpcbind=0.0.0.0'
      - '-rpcauth=foo:d5268f9f980d9cc37c47bb2e64bdc4c4$$2f919b85988524201e472d2421530757ed140a32cc483d04ad00f1a1da2ded85'
    networks:
      - docknode-btc

  nodeexporter:
    image: prom/node-exporter:v1.4.0
    container_name: nodeexporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - docknode-btc

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    depends_on:
      - bitcoind
    ports:
      - "80:80"
      - "443:443"
      - "9100:9100"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - BASIC_AUTH_USERS=${BASIC_AUTH_USERS:?err}
      - HOST=${HOST:?err}
    networks:
      - docknode-btc