auth="foo:tdhgGzvP6BJw_piFGHh5JLnQWyWd2wcExHCwKTnkaYo="
daemon_rpc_addr = "bitcoind:8332"
daemon_p2p_addr = "bitcoind:8333"
db_dir = "/electrs/db"
network = "bitcoin"
electrum_rpc_addr = "127.0.0.1:50001"
log_filters = "INFO"