auth="foo:tdhgGzvP6BJw_piFGHh5JLnQWyWd2wcExHCwKTnkaYo="
daemon_dir= "/data/.bitcoin"
daemon_rpc_addr = "bitcoind:8332"
daemon_p2p_addr = "bitcoind:8333"
db_dir = "/electrs/db"
network = "bitcoin"
electrum_rpc_addr = "0.0.0.0:50001"
log_filters = "INFO"
sync_once = true